# Generated by Django 4.2.16 on 2026-09-18 09:50

import apps.orders.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        default=apps.orders.models.generate_order_number,
                        editable=False,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("PICKUP", "Pickup"),
                            ("DELIVERY", "Delivery"),
                            ("DINE_IN", "Dine In"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLACED", "Order Placed"),
                            ("CONFIRMED", "Order Confirmed"),
                            ("PREPARING", "Preparing"),
                            ("READY", "Ready"),
                            ("OUT_FOR_DELIVERY", "Out for Delivery"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PLACED",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("coupon_code", models.CharField(blank=True, max_length=50, null=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estimated_preparation_time_minutes", models.IntegerField(default=30)),
                (
                    "estimated_delivery_time_minutes",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "actual_delivery_time_minutes",
                    models.IntegerField(blank=True, null=True),
                ),
                ("customer_notes", models.TextField(blank=True, null=True)),
                ("special_instructions", models.TextField(blank=True, null=True)),
                ("placed_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancellation_reason",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("delivery_address", models.TextField(blank=True, null=True)),
                (
                    "delivery_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "delivery_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "delivery_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "delivery_postal_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "delivery_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "delivery_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("delivery_instructions", models.TextField(blank=True, null=True)),
                ("pickup_time", models.DateTimeField(blank=True, null=True)),
                (
                    "table_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("number_of_guests", models.IntegerField(blank=True, null=True)),
                ("is_scheduled", models.BooleanField(default=False)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["-placed_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=200)),
                ("item_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("quantity", models.IntegerField(default=1)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("special_instructions", models.TextField(blank=True, null=True)),
                (
                    "menu_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="menu.menuitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItemCustomization",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("customization_name", models.CharField(max_length=100)),
                ("option_name", models.CharField(max_length=100)),
                (
                    "price_modifier",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customizations",
                        to="orders.orderitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItemAddOn",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("addon_name", models.CharField(max_length=100)),
                ("addon_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addons",
                        to="orders.orderitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer"], name="orders_orde_custome_59b6fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["restaurant"], name="orders_orde_restaur_79a0fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="orders_orde_status_c6dd84_idx"),
        ),
    ]
