# Generated by Django 4.2.16 on 2026-09-29 19:10

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                default=apps.orders.models.generate_order_number,
                editable=False,
                max_length=30,
                unique=True,
            ),
        ),
    ]
