# Generated by Django 4.2.16 on 2026-09-29 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
        ("orders", "0003_alter_order_subtotal_alter_order_total_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="restaurants.restaurant",
            ),
        ),
    ]
