# Generated by Django 4.2.13 on 2026-10-07 08:35

import apps.support.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='ticket_id',
            field=models.CharField(default=apps.support.models.generate_ticket_id, editable=False, max_length=30, unique=True),
        ),
    ]
