# Generated by Django 4.2.16 on 2026-09-18 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopularItemReport",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField()),
                ("times_ordered", models.IntegerField(default=0)),
                ("total_quantity_sold", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="menu.menuitem"
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="popular_items",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date", "-times_ordered"],
                "unique_together": {("restaurant", "menu_item", "report_date")},
            },
        ),
        migrations.CreateModel(
            name="DailySalesReport",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField()),
                ("total_orders", models.IntegerField(default=0)),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "average_order_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_customers", models.IntegerField(default=0)),
                ("new_customers", models.IntegerField(default=0)),
                (
                    "total_refunds",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("cancelled_orders", models.IntegerField(default=0)),
                ("completed_orders", models.IntegerField(default=0)),
                ("average_preparation_time_minutes", models.IntegerField(default=0)),
                (
                    "average_delivery_time_minutes",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reports",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date"],
                "unique_together": {("restaurant", "report_date")},
            },
        ),
        migrations.CreateModel(
            name="CustomerAnalytics",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("total_orders", models.IntegerField(default=0)),
                (
                    "total_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "average_order_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("last_order_date", models.DateField(blank=True, null=True)),
                ("days_since_last_order", models.IntegerField(blank=True, null=True)),
                (
                    "customer_lifetime_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_returning_customer", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "unique_together": {("customer", "restaurant")},
            },
        ),
    ]
